FROM python:3.9.6
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
#CMD ["python", "main.py"]
EXPOSE 7860
# Set the command to execute your Python file
ENV GRADIO_SERVER_NAME="0.0.0.0"
CMD ["gradio", "__init__.py"]
